export const products = [
  {
    id: 1,
    productImg:
      "https://chaldn.com/_mpimage/mango-aamropali-net-weight-50-gm-3-kg?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D79768&q=low&v=1&m=400&webp=1",
    productName: "Mango Aamropali (Net Weight ± 50 gm)",
    uom: "Kg",
    amount: 3,
    price: 239,
    discountPrice: 239,
    oldPrice: 269,
    category: "fruits-vegetables",
    brand: "ABC",
  },
  {
    id: 2,
    productImg:
      "https://chaldn.com/_mpimage/cherry-pineapple-1-pcs?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D77400&q=low&v=1&m=400&webp=1",
    productName: "Cherry Pineapple",
    uom: "pcs",
    amount: 1,
    price: 15,
    discountPrice: 15,
    oldPrice: 19,
    category: "fruits-vegetables",
    brand: "ABC",
  },
  {
    id: 3,
    productImg:
      "https://chaldn.com/_mpimage/paka-pape-net-weight-50-gm-1-kg?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D23193&q=low&v=1&m=400&webp=1",
    productName: "Paka Pape (Net Weight ± 50 gm)",
    uom: "Kg",
    amount: 1,
    price: 149,
    discountPrice: 149,
    oldPrice: 149,
    category: "fruits-vegetables",
    brand: "ABC",
  },
  {
    id: 4,
    productImg:
      "https://chaldn.com/_mpimage/sapodilla-sofeda-1-kg?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D18391&q=low&v=1&m=400&m=400&webp=1",
    productName: "Sapodilla (Sofeda)",
    uom: "kg",
    amount: 1,
    price: 99,
    discountPrice: 99,
    oldPrice: 139,
    category: "fruits-vegetables",
    brand: "ABC",
  },
  {
    id: 5,
    productImg:
      "https://chaldn.com/_mpimage/sapodilla-sofeda-1-kg?src=https%3A%2F%2Feggyolk.chaldal.com%2Fapi%2FPicture%2FRaw%3FpictureId%3D18391&q=low&v=1&m=400&m=400&webp=1",
    productName: "Sapodilla (Sofeda)",
    uom: "kg",
    amount: 1,
    price: 99,
    discountPrice: 99,
    oldPrice: 139,
    category: "fruits-vegetables",
    brand: "ABC",
  },
];
